/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainRouteRouteImport } from './routes/__main/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _mainIndexRouteImport } from './routes/__main/index'
import { Route as _mainUserManagementRouteImport } from './routes/__main/user-management'
import { Route as _mainSettingsRouteImport } from './routes/__main/settings'
import { Route as _mainRoleManagementRouteImport } from './routes/__main/role-management'
import { Route as _mainReviewsRouteImport } from './routes/__main/reviews'
import { Route as _mainReservationsRouteImport } from './routes/__main/reservations'
import { Route as _mainReportsRouteImport } from './routes/__main/reports'
import { Route as _mainPropertyRouteImport } from './routes/__main/property'
import { Route as _mainPaymentsRouteImport } from './routes/__main/payments'
import { Route as _mainInboxRouteImport } from './routes/__main/inbox'
import { Route as _mainEmployeesRouteImport } from './routes/__main/employees'
import { Route as _mainChannelManagerRouteImport } from './routes/__main/channel-manager'
import { Route as _mainCalendarRouteImport } from './routes/__main/calendar'
import { Route as _authVerificationRouteImport } from './routes/__auth/verification'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as _mainSupportIndexRouteImport } from './routes/__main/support.index'
import { Route as _mainSupportIdRouteImport } from './routes/__main/support.$id'
import { Route as _mainReportsSourceRouteImport } from './routes/__main/reports_.$source'
import { Route as _mainPropertyPropertySlugRouteImport } from './routes/__main/property_.$propertySlug'
import { Route as _mainPropertyPropertySlugRoomRoomSlugRouteImport } from './routes/__main/property_.$propertySlug_.room.$roomSlug'

const _mainRouteRoute = _mainRouteRouteImport.update({
  id: '/__main',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainIndexRoute = _mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainUserManagementRoute = _mainUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSettingsRoute = _mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainRoleManagementRoute = _mainRoleManagementRouteImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainReviewsRoute = _mainReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainReservationsRoute = _mainReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainReportsRoute = _mainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainPropertyRoute = _mainPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainPaymentsRoute = _mainPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainInboxRoute = _mainInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainEmployeesRoute = _mainEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainChannelManagerRoute = _mainChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainCalendarRoute = _mainCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _authVerificationRoute = _authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _mainSupportIndexRoute = _mainSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSupportIdRoute = _mainSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainReportsSourceRoute = _mainReportsSourceRouteImport.update({
  id: '/reports_/$source',
  path: '/reports/$source',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainPropertyPropertySlugRoute =
  _mainPropertyPropertySlugRouteImport.update({
    id: '/property_/$propertySlug',
    path: '/property/$propertySlug',
    getParentRoute: () => _mainRouteRoute,
  } as any)
const _mainPropertyPropertySlugRoomRoomSlugRoute =
  _mainPropertyPropertySlugRoomRoomSlugRouteImport.update({
    id: '/property_/$propertySlug_/room/$roomSlug',
    path: '/property/$propertySlug/room/$roomSlug',
    getParentRoute: () => _mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/calendar': typeof _mainCalendarRoute
  '/channel-manager': typeof _mainChannelManagerRoute
  '/employees': typeof _mainEmployeesRoute
  '/inbox': typeof _mainInboxRoute
  '/payments': typeof _mainPaymentsRoute
  '/property': typeof _mainPropertyRoute
  '/reports': typeof _mainReportsRoute
  '/reservations': typeof _mainReservationsRoute
  '/reviews': typeof _mainReviewsRoute
  '/role-management': typeof _mainRoleManagementRoute
  '/settings': typeof _mainSettingsRoute
  '/user-management': typeof _mainUserManagementRoute
  '/property/$propertySlug': typeof _mainPropertyPropertySlugRoute
  '/reports/$source': typeof _mainReportsSourceRoute
  '/support/$id': typeof _mainSupportIdRoute
  '/support/': typeof _mainSupportIndexRoute
  '/property/$propertySlug/room/$roomSlug': typeof _mainPropertyPropertySlugRoomRoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/calendar': typeof _mainCalendarRoute
  '/channel-manager': typeof _mainChannelManagerRoute
  '/employees': typeof _mainEmployeesRoute
  '/inbox': typeof _mainInboxRoute
  '/payments': typeof _mainPaymentsRoute
  '/property': typeof _mainPropertyRoute
  '/reports': typeof _mainReportsRoute
  '/reservations': typeof _mainReservationsRoute
  '/reviews': typeof _mainReviewsRoute
  '/role-management': typeof _mainRoleManagementRoute
  '/settings': typeof _mainSettingsRoute
  '/user-management': typeof _mainUserManagementRoute
  '/property/$propertySlug': typeof _mainPropertyPropertySlugRoute
  '/reports/$source': typeof _mainReportsSourceRoute
  '/support/$id': typeof _mainSupportIdRoute
  '/support': typeof _mainSupportIndexRoute
  '/property/$propertySlug/room/$roomSlug': typeof _mainPropertyPropertySlugRoomRoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__main': typeof _mainRouteRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/verification': typeof _authVerificationRoute
  '/__main/calendar': typeof _mainCalendarRoute
  '/__main/channel-manager': typeof _mainChannelManagerRoute
  '/__main/employees': typeof _mainEmployeesRoute
  '/__main/inbox': typeof _mainInboxRoute
  '/__main/payments': typeof _mainPaymentsRoute
  '/__main/property': typeof _mainPropertyRoute
  '/__main/reports': typeof _mainReportsRoute
  '/__main/reservations': typeof _mainReservationsRoute
  '/__main/reviews': typeof _mainReviewsRoute
  '/__main/role-management': typeof _mainRoleManagementRoute
  '/__main/settings': typeof _mainSettingsRoute
  '/__main/user-management': typeof _mainUserManagementRoute
  '/__main/': typeof _mainIndexRoute
  '/__main/property_/$propertySlug': typeof _mainPropertyPropertySlugRoute
  '/__main/reports_/$source': typeof _mainReportsSourceRoute
  '/__main/support/$id': typeof _mainSupportIdRoute
  '/__main/support/': typeof _mainSupportIndexRoute
  '/__main/property_/$propertySlug_/room/$roomSlug': typeof _mainPropertyPropertySlugRoomRoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/calendar'
    | '/channel-manager'
    | '/employees'
    | '/inbox'
    | '/payments'
    | '/property'
    | '/reports'
    | '/reservations'
    | '/reviews'
    | '/role-management'
    | '/settings'
    | '/user-management'
    | '/property/$propertySlug'
    | '/reports/$source'
    | '/support/$id'
    | '/support/'
    | '/property/$propertySlug/room/$roomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/calendar'
    | '/channel-manager'
    | '/employees'
    | '/inbox'
    | '/payments'
    | '/property'
    | '/reports'
    | '/reservations'
    | '/reviews'
    | '/role-management'
    | '/settings'
    | '/user-management'
    | '/property/$propertySlug'
    | '/reports/$source'
    | '/support/$id'
    | '/support'
    | '/property/$propertySlug/room/$roomSlug'
  id:
    | '__root__'
    | '/__auth'
    | '/__main'
    | '/__auth/forgot-password'
    | '/__auth/reset-password'
    | '/__auth/signin'
    | '/__auth/verification'
    | '/__main/calendar'
    | '/__main/channel-manager'
    | '/__main/employees'
    | '/__main/inbox'
    | '/__main/payments'
    | '/__main/property'
    | '/__main/reports'
    | '/__main/reservations'
    | '/__main/reviews'
    | '/__main/role-management'
    | '/__main/settings'
    | '/__main/user-management'
    | '/__main/'
    | '/__main/property_/$propertySlug'
    | '/__main/reports_/$source'
    | '/__main/support/$id'
    | '/__main/support/'
    | '/__main/property_/$propertySlug_/room/$roomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _mainRouteRoute: typeof _mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/user-management': {
      id: '/__main/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof _mainUserManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/settings': {
      id: '/__main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _mainSettingsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/role-management': {
      id: '/__main/role-management'
      path: '/role-management'
      fullPath: '/role-management'
      preLoaderRoute: typeof _mainRoleManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/reviews': {
      id: '/__main/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof _mainReviewsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/reservations': {
      id: '/__main/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof _mainReservationsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/reports': {
      id: '/__main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof _mainReportsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/property': {
      id: '/__main/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof _mainPropertyRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/payments': {
      id: '/__main/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof _mainPaymentsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/inbox': {
      id: '/__main/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof _mainInboxRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/employees': {
      id: '/__main/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof _mainEmployeesRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/channel-manager': {
      id: '/__main/channel-manager'
      path: '/channel-manager'
      fullPath: '/channel-manager'
      preLoaderRoute: typeof _mainChannelManagerRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/calendar': {
      id: '/__main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof _mainCalendarRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__auth/verification': {
      id: '/__auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof _authVerificationRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__main/support/': {
      id: '/__main/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof _mainSupportIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/support/$id': {
      id: '/__main/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof _mainSupportIdRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/reports_/$source': {
      id: '/__main/reports_/$source'
      path: '/reports/$source'
      fullPath: '/reports/$source'
      preLoaderRoute: typeof _mainReportsSourceRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/property_/$propertySlug': {
      id: '/__main/property_/$propertySlug'
      path: '/property/$propertySlug'
      fullPath: '/property/$propertySlug'
      preLoaderRoute: typeof _mainPropertyPropertySlugRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/property_/$propertySlug_/room/$roomSlug': {
      id: '/__main/property_/$propertySlug_/room/$roomSlug'
      path: '/property/$propertySlug/room/$roomSlug'
      fullPath: '/property/$propertySlug/room/$roomSlug'
      preLoaderRoute: typeof _mainPropertyPropertySlugRoomRoomSlugRouteImport
      parentRoute: typeof _mainRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSigninRoute: typeof _authSigninRoute
  _authVerificationRoute: typeof _authVerificationRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSigninRoute: _authSigninRoute,
  _authVerificationRoute: _authVerificationRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _mainRouteRouteChildren {
  _mainCalendarRoute: typeof _mainCalendarRoute
  _mainChannelManagerRoute: typeof _mainChannelManagerRoute
  _mainEmployeesRoute: typeof _mainEmployeesRoute
  _mainInboxRoute: typeof _mainInboxRoute
  _mainPaymentsRoute: typeof _mainPaymentsRoute
  _mainPropertyRoute: typeof _mainPropertyRoute
  _mainReportsRoute: typeof _mainReportsRoute
  _mainReservationsRoute: typeof _mainReservationsRoute
  _mainReviewsRoute: typeof _mainReviewsRoute
  _mainRoleManagementRoute: typeof _mainRoleManagementRoute
  _mainSettingsRoute: typeof _mainSettingsRoute
  _mainUserManagementRoute: typeof _mainUserManagementRoute
  _mainIndexRoute: typeof _mainIndexRoute
  _mainPropertyPropertySlugRoute: typeof _mainPropertyPropertySlugRoute
  _mainReportsSourceRoute: typeof _mainReportsSourceRoute
  _mainSupportIdRoute: typeof _mainSupportIdRoute
  _mainSupportIndexRoute: typeof _mainSupportIndexRoute
  _mainPropertyPropertySlugRoomRoomSlugRoute: typeof _mainPropertyPropertySlugRoomRoomSlugRoute
}

const _mainRouteRouteChildren: _mainRouteRouteChildren = {
  _mainCalendarRoute: _mainCalendarRoute,
  _mainChannelManagerRoute: _mainChannelManagerRoute,
  _mainEmployeesRoute: _mainEmployeesRoute,
  _mainInboxRoute: _mainInboxRoute,
  _mainPaymentsRoute: _mainPaymentsRoute,
  _mainPropertyRoute: _mainPropertyRoute,
  _mainReportsRoute: _mainReportsRoute,
  _mainReservationsRoute: _mainReservationsRoute,
  _mainReviewsRoute: _mainReviewsRoute,
  _mainRoleManagementRoute: _mainRoleManagementRoute,
  _mainSettingsRoute: _mainSettingsRoute,
  _mainUserManagementRoute: _mainUserManagementRoute,
  _mainIndexRoute: _mainIndexRoute,
  _mainPropertyPropertySlugRoute: _mainPropertyPropertySlugRoute,
  _mainReportsSourceRoute: _mainReportsSourceRoute,
  _mainSupportIdRoute: _mainSupportIdRoute,
  _mainSupportIndexRoute: _mainSupportIndexRoute,
  _mainPropertyPropertySlugRoomRoomSlugRoute:
    _mainPropertyPropertySlugRoomRoomSlugRoute,
}

const _mainRouteRouteWithChildren = _mainRouteRoute._addFileChildren(
  _mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _mainRouteRoute: _mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
