/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainRouteRouteImport } from './routes/__main/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _mainIndexRouteImport } from './routes/__main/index'
import { Route as _mainSettingsRouteImport } from './routes/__main/settings'
import { Route as _mainRoleManagementRouteImport } from './routes/__main/role-management'
import { Route as _mainEmployeesRouteImport } from './routes/__main/employees'
import { Route as _authVerificationRouteImport } from './routes/__auth/verification'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as _mainSupportIndexRouteImport } from './routes/__main/support.index'
import { Route as _mainSupportIdRouteImport } from './routes/__main/support.$id'

const _mainRouteRoute = _mainRouteRouteImport.update({
  id: '/__main',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainIndexRoute = _mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSettingsRoute = _mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainRoleManagementRoute = _mainRoleManagementRouteImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainEmployeesRoute = _mainEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _authVerificationRoute = _authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _mainSupportIndexRoute = _mainSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSupportIdRoute = _mainSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => _mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/employees': typeof _mainEmployeesRoute
  '/role-management': typeof _mainRoleManagementRoute
  '/settings': typeof _mainSettingsRoute
  '/support/$id': typeof _mainSupportIdRoute
  '/support/': typeof _mainSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/employees': typeof _mainEmployeesRoute
  '/role-management': typeof _mainRoleManagementRoute
  '/settings': typeof _mainSettingsRoute
  '/support/$id': typeof _mainSupportIdRoute
  '/support': typeof _mainSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__main': typeof _mainRouteRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/verification': typeof _authVerificationRoute
  '/__main/employees': typeof _mainEmployeesRoute
  '/__main/role-management': typeof _mainRoleManagementRoute
  '/__main/settings': typeof _mainSettingsRoute
  '/__main/': typeof _mainIndexRoute
  '/__main/support/$id': typeof _mainSupportIdRoute
  '/__main/support/': typeof _mainSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/employees'
    | '/role-management'
    | '/settings'
    | '/support/$id'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/employees'
    | '/role-management'
    | '/settings'
    | '/support/$id'
    | '/support'
  id:
    | '__root__'
    | '/__auth'
    | '/__main'
    | '/__auth/forgot-password'
    | '/__auth/reset-password'
    | '/__auth/signin'
    | '/__auth/verification'
    | '/__main/employees'
    | '/__main/role-management'
    | '/__main/settings'
    | '/__main/'
    | '/__main/support/$id'
    | '/__main/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _mainRouteRoute: typeof _mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/settings': {
      id: '/__main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _mainSettingsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/role-management': {
      id: '/__main/role-management'
      path: '/role-management'
      fullPath: '/role-management'
      preLoaderRoute: typeof _mainRoleManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/employees': {
      id: '/__main/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof _mainEmployeesRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__auth/verification': {
      id: '/__auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof _authVerificationRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__main/support/': {
      id: '/__main/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof _mainSupportIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/support/$id': {
      id: '/__main/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof _mainSupportIdRouteImport
      parentRoute: typeof _mainRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSigninRoute: typeof _authSigninRoute
  _authVerificationRoute: typeof _authVerificationRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSigninRoute: _authSigninRoute,
  _authVerificationRoute: _authVerificationRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _mainRouteRouteChildren {
  _mainEmployeesRoute: typeof _mainEmployeesRoute
  _mainRoleManagementRoute: typeof _mainRoleManagementRoute
  _mainSettingsRoute: typeof _mainSettingsRoute
  _mainIndexRoute: typeof _mainIndexRoute
  _mainSupportIdRoute: typeof _mainSupportIdRoute
  _mainSupportIndexRoute: typeof _mainSupportIndexRoute
}

const _mainRouteRouteChildren: _mainRouteRouteChildren = {
  _mainEmployeesRoute: _mainEmployeesRoute,
  _mainRoleManagementRoute: _mainRoleManagementRoute,
  _mainSettingsRoute: _mainSettingsRoute,
  _mainIndexRoute: _mainIndexRoute,
  _mainSupportIdRoute: _mainSupportIdRoute,
  _mainSupportIndexRoute: _mainSupportIndexRoute,
}

const _mainRouteRouteWithChildren = _mainRouteRoute._addFileChildren(
  _mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _mainRouteRoute: _mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
